[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "custom-plotting-library"
version = "1.0.0"
dependencies = ["pandas", "numpy", "matplotlib"]
requires-python = ">=3.11"
authors = [
  {name = "gjkhai"}
]




